### ISSUE TITLE
Move away from using MD5 hashing

### ISSUE THREAD

**Issue by ascheid** [cds-snc/scan-files#411]
MD5 is not considered a secure hashing algorithm anymore. 

We are using MD5 for hashing through our code to verify/compare files.

Ie. [scan-files](https://github.com/cds-snc/scan-files)/[api](https://github.com/cds-snc/scan-files/tree/main/api)/[clamav_scanner](https://github.com/cds-snc/scan-files/tree/main/api/clamav_scanner)/clamav.py

**Comment by patheard** [comment]
Related to the [`clamav.py`](https://github.com/cds-snc/scan-files/blob/main/api/clamav_scanner/clamav.py) use of MD5, that was added to check if we should perform tasks rather than trying to add any security improvements.  I suspect it was used over something like SHA256 because of speed and size considerations:

> `MD5:` The fastest and shortest generated hash (16 bytes). The probability of just two hashes accidentally colliding is approximately: 1.47*10-29.
>
> `SHA1:` Is generally 20% slower than md5, the generated hash is a bit longer than MD5 (20 bytes). The probability of just two hashes accidentally colliding is approximately: 1*10-45
>
> `SHA256:` The slowest, usually 60% slower than md5, and the longest generated hash (32 bytes). The probability of just two hashes accidentally colliding is approximately: 4.3*10-60.

I'm glad you raised this though because we should definitely go over the code an make sure we're not using MD5 anywhere that has a security implication.

**Comment by patheard** [comment]
Closing as we're not using MD5 hashing anywhere for security related functions.
